### ISSUE TITLE
keys generated are invalid

### ISSUE THREAD

**Issue by coder797** [FLUORESCENTXX/ExpressVPN-Activation-Code-Generator#1]
it shows the keys are invalid "Your activation code is invalid"

**Comment by FLUORESCENTXX** [comment]
It says

**Comment by coder797** [comment]
when I enter these keys in express VPN app it shows they are invalid

**Comment by FLUORESCENTXX** [comment]
They aren’t all valid lmao

**Comment by loveyoursupport** [comment]
btw how to find webhook link from discord?
and obviously we need a checked for checking keys because it generate randomly all keys.

**Comment by FLUORESCENTXX** [comment]
Make ome
