### ISSUE TITLE
Code doesnt work

### ISSUE THREAD

**Issue by mrcranezs** [FLUORESCENTXX/ExpressVPN-Activation-Code-Generator#2]
I might be stupid, because i am unfamiliar with python or any coding languages but when i put in pip: -r requirements.txt. into the shell and entering it responds with SyntaxError: invalid syntax and highlights the r in requirements. I am running python 3.10.4 and an m1 mac.

**Comment by FLUORESCENTXX** [comment]
Alr

**Comment by FLUORESCENTXX** [comment]
Then install the modules in main.py
